Change back to non-docker-compose

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -66,15 +66,15 @@ EOF
 #------------------------------------------------------------------------------------
 # Run a command in a temporary container.
 
-# function dockerrun {
-#    local RVAL=0
-#    local ENVOPTS=("-e" "VAULT_ADDR=${VAULT_ADDR}" "-e" "VAULT_TOKEN=${VAULT_TOKEN}" "-e" "VAULT_CONTEXT=${VAULT_CONTEXT}")
-#    local DOCKERVOLS=("-v" "drunner-${SERVICENAME}-config:/config")
-#    docker run "${COMMANDOPTS[@]}" "${ENVOPTS[@]}" "${DOCKERVOLS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${IMAGENAME}" "$@"
-#    RVAL=$?
-#    docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
-#    [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
-# }
+function dockerrun {
+   local RVAL=0
+   local ENVOPTS=("-e" "VAULT_ADDR=${VAULT_ADDR}" "-e" "VAULT_TOKEN=${VAULT_TOKEN}" "-e" "VAULT_CONTEXT=${VAULT_CONTEXT}")
+   local DOCKERVOLS=("-v" "drunner-${SERVICENAME}-config:/config")
+   docker run "${COMMANDOPTS[@]}" "${ENVOPTS[@]}" "${DOCKERVOLS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${IMAGENAME}" "$@"
+   RVAL=$?
+   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
+   [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
+}
 
 #------------------------------------------------------------------------------------
 # The main function. We can add any commands we'd like here!
@@ -84,9 +84,6 @@ function main {
 
    COMMAND="${1}"
    COMMANDOPTS=("-i")
-   
-   # default to something safe
-   LOAD_VOLUME="${SERVICETEMPDIR}"
 
    case "$COMMAND" in
 
@@ -98,7 +95,8 @@ function main {
 
          enter)
             shift
-            docker-compose -p -e "LOAD_VOLUME=${LOAD_VOLUME}" "${SERVICENAME}" run dvault /bin/bash "$@"
+            COMMANDOPTS=("-it")
+            dockerrun /bin/bash "$@"
             ;;
 
          #--- custom commands
@@ -118,8 +116,9 @@ function main {
             if [ ! -z "${4:-}" ]; then CONTAINER_UID="${4}"; else CONTAINER_UID="0"; fi
             if [ ! -z "${5:-}" ]; then CONTAINER_GID="${5}"; else CONTAINER_GID="0"; fi
 
-            LOAD_VOLUME="$3"
-            docker-compose -pT -e "LOAD_VOLUME=${LOAD_VOLUME}" "${SERVICENAME}" run dvault-load vault-load-wrapper.sh "$2" "$CONTAINER_UID" "$CONTAINER_GID"
+            OUTPUT_VOLUME="$3"
+            COMMANDOPTS=("-v" "$OUTPUT_VOLUME:/output")
+            dockerrun vault-load-wrapper.sh "$2" "$CONTAINER_UID" "$CONTAINER_GID"
             echo "Secrets loaded for ${2}"
             ;;
 
@@ -129,20 +128,20 @@ function main {
             FILENAME=$(basename $SECRET_FILE)
             [ -f "${SECRET_FILE}" ] || die "Not a file: ${SECRET_FILE}"
 
-            LOAD_VOLUME="${SECRET_FILE}"
-            docker-compose -pT -e "LOAD_VOLUME=${LOAD_VOLUME}" "${SERVICENAME}" "--user=\"$(id -u):$(id -g)\"" run dvault-load bash -c "vault write secret/dvault/\$VAULT_CONTEXT/${2}/${FILENAME} value=@/load"
+            COMMANDOPTS=("--user=\"$(id -u):$(id -g)\"" "-v" "${SECRET_FILE}:/import/secret:ro")
+            dockerrun bash -c "vault write secret/dvault/\$VAULT_CONTEXT/${2}/${FILENAME} value=@/import/secret"
             ;;
 
           list)
             [ ! -z "${2:-}" ] || die "Usage: ${SERVICENAME} ls PROJECT"
 
-            docker-compose -pT -e "LOAD_VOLUME=${LOAD_VOLUME}" "${SERVICENAME}" "--user=\"$(id -u):$(id -g)\"" run dvault bash -c "echo \"${CODE_S}Secrets in '\${VAULT_CONTEXT}' context${CODE_E}\"; vault list secret/dvault/\$VAULT_CONTEXT/${2}"
+            dockerrun bash -c "echo \"${CODE_S}Secrets in '\${VAULT_CONTEXT}' context${CODE_E}\"; vault list secret/dvault/\$VAULT_CONTEXT/${2}"
             ;;
 
           delete)
             [ ! -z "${3:-}" ] || die "Usage: ${SERVICENAME} delete PROJECT SECRET"
 
-            docker-compose -pT -e "LOAD_VOLUME=${LOAD_VOLUME}" "${SERVICENAME}" "--user=\"$(id -u):$(id -g)\"" run dvault bash -c "vault delete secret/dvault/\$VAULT_CONTEXT/${2}/${3}"
+            dockerrun bash -c "vault delete secret/dvault/\$VAULT_CONTEXT/${2}/${3}"
             ;;
 
           context)
@@ -159,8 +158,8 @@ function main {
             CONFIG_FILE=$(realpath $2)
             [ -f "${CONFIG_FILE}" ] || die "Not a file: ${CONFIG_FILE}"
 
-            LOAD_VOLUME="${CONFIG_FILE}"
-            docker-compose -pT -e "LOAD_VOLUME=${LOAD_VOLUME}" "${SERVICENAME}" "--user=\"$(id -u):$(id -g)\"" run dvault-load import.py
+            COMMANDOPTS=("--user=\"$(id -u):$(id -g)\"" "-v" "${CONFIG_FILE}:/import/config.json:ro")
+            dockerrun import.py
             ;;
 
          #--- unrecognised commands
