First cut

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -36,6 +36,12 @@ SYNOPSIS
    ${CODE_S}${SERVICENAME} help${CODE_E}
       This help.
    
+   ${CODE_S}VAULT_ADDR=? VAULT_TOKEN=? ${SERVICENAME} configure${CODE_E}
+      Configure Vault
+   
+   ${CODE_S}${SERVICENAME} load CONFIG${CODE_E}
+      Load vault values into configuration volume
+   
 DESCRIPTION
    Helpers for dvault. Built from ${IMAGENAME}.
    
@@ -48,7 +54,7 @@ EOF
 
 function dockerrun {
    local RVAL=0
-   docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${IMAGENAME}" "$@"
+   docker run "${COMMANDOPTS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}" "$@"
    RVAL=$?
    docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
    [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
@@ -152,7 +158,22 @@ function main {
             ;;
             
          #--- custom commands
-
+         
+         configure)
+            [ ! -z "${VAULT_ADDR:-}" ] || die "Vault Address not found, please run ${CODE_S}VAULT_ADDR=? VAULT_TOKEN=? ${SERVICENAME} configure${CODE_E}"
+            [ ! -z "${VAULT_TOKEN:-}" ] || die "Vault Token not found, please run ${CODE_S}VAULT_ADDR=? VAULT_TOKEN=? ${SERVICENAME} configure${CODE_E}"
+            COMMANDOPTS=("-e" "VAULT_ADDR=$VAULT_ADDR" "-e" "VAULT_TOKEN=$VAULT_TOKEN")
+            dockerrun configure
+            ;;
+            
+         load)
+            [ ! -z "${2:-}" ] || die "Usage: ${SERVICENAME} load CONFIG"
+            local VAULT_CONFIG_FILE="$(realpath $2)"
+            COMMANDOPTS=("-v" "$VAULT_CONFIG_FILE:/import/config.json:ro")
+            local OUTPUT_VOLUME="$(dockerrun volume.py)"
+            COMMANDOPTS=("-v" "$VAULT_CONFIG_FILE:/import/config.json:ro" "-v" "$OUTPUT_VOLUME:/output")
+            dockerrun vault-load.py
+            ;;
             
          #--- unrecognised commands
 
