Update to use docker-compose properly

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -66,15 +66,15 @@ EOF
 #------------------------------------------------------------------------------------
 # Run a command in a temporary container.
 
-function dockerrun {
-   local RVAL=0
-   local ENVOPTS=("-e" "VAULT_ADDR=${VAULT_ADDR}" "-e" "VAULT_TOKEN=${VAULT_TOKEN}" "-e" "VAULT_CONTEXT=${VAULT_CONTEXT}")
-   local DOCKERVOLS=("-v" "drunner-${SERVICENAME}-config:/config")
-   docker run "${COMMANDOPTS[@]}" "${ENVOPTS[@]}" "${DOCKERVOLS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${IMAGENAME}" "$@"
-   RVAL=$?
-   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
-   [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
-}
+# function dockerrun {
+#    local RVAL=0
+#    local ENVOPTS=("-e" "VAULT_ADDR=${VAULT_ADDR}" "-e" "VAULT_TOKEN=${VAULT_TOKEN}" "-e" "VAULT_CONTEXT=${VAULT_CONTEXT}")
+#    local DOCKERVOLS=("-v" "drunner-${SERVICENAME}-config:/config")
+#    docker run "${COMMANDOPTS[@]}" "${ENVOPTS[@]}" "${DOCKERVOLS[@]}" --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${IMAGENAME}" "$@"
+#    RVAL=$?
+#    docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
+#    [ $RVAL -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
+# }
 
 #------------------------------------------------------------------------------------
 # The main function. We can add any commands we'd like here!
@@ -84,6 +84,9 @@ function main {
 
    COMMAND="${1}"
    COMMANDOPTS=("-i")
+   
+   # default to something safe
+   OUTPUT_VOLUME=${SERVICETEMPDIR}
 
    case "$COMMAND" in
 
@@ -95,8 +98,7 @@ function main {
 
          enter)
             shift
-            COMMANDOPTS=("-it")
-            dockerrun /bin/bash "$@"
+            docker-compose -p "${SERVICENAME}" run dvault /bin/bash "$@"
             ;;
 
          #--- custom commands
@@ -117,9 +119,7 @@ function main {
             if [ ! -z "${5:-}" ]; then CONTAINER_GID="${5}"; else CONTAINER_GID="0"; fi
 
             OUTPUT_VOLUME="$3"
-
-            COMMANDOPTS=("-v" "$OUTPUT_VOLUME:/output")
-            dockerrun vault-load-wrapper.sh "$2" "$CONTAINER_UID" "$CONTAINER_GID"
+            docker-compose -p "${SERVICENAME}" run dvault-load vault-load-wrapper.sh "$2" "$CONTAINER_UID" "$CONTAINER_GID"
             echo "Secrets loaded for ${2}"
             ;;
 
